name: fastowebrtc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_webrtc_sdk:
    git:
      url: https://gitlab.com/fastogt/flutter_webrtc_sdk.git
      ref: main
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  http:

dev_dependencies:
  dart_rules:
    git:
      url: https://github.com/fastogt/dart_rules.git
      ref: main
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
